version: '3'
services:
  database:
    container_name: database_container
    build:
      context: ./database/pgsql
    restart: always
    ports:
      - "5432:5432"
    # delete this if you want ephemeral database
#    volumes:
#      - /Users/asarioglo/misc/mariadb_files:/var/lib/mysql
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=appUser
    expose:
      - '5432'
